### ISSUE TITLE
Installation via Brat

### ISSUE THREAD

**Issue by dxcore35** [patleeman/obsidian-readability#1]
Please add installation via Brat. It will help you find users to test your code.

**Comment by simsalis** [comment]
Hi. I actually do not know how to install this :D I tried to find a main.js to manually copy in a plugins subfolder, or even installing NPM, but no success. :/

**Comment by dxcore35** [comment]
I also tried to rename `.ts` files to `.js` but they will not appear in Obsidian plugin section....

**Comment by patleeman** [comment]
Hi all, thanks for the feedback. I've released `0.0.1` which should now be install-able using obsidian-BRAT.
